### PR TITLE
Version 3.0.0

### PR DESCRIPTION
**Pull request by PMunch**
Basically rewrote most of xlunch. Added a bunch of options, a new render mode (text beside the icons), completely new calculation of where to draw things, options to set most colors, option to set both the prompt font and the title font separately, option to only output selection. The application now handles recur to do what the old xlunch did to respawn itself, otherwise runs all commands in bash. It also has the ability to take input over stdin, which combined with the output option will make it work more or less like dmenu. Added a .desktop file for genentries (old genconf) so that you can run a refresh of the entries from xlunch. The script now searches more folders in a more proper order, and reads .local/share/applications before /usr/share/applications to let the user override their .desktop files. Added some X11 things like a proper WM_CLASS. Made it behave better with --name, --help, and --version. Rewrote all options to have both a long and a short option.

THIS BREAKS BACKWARDS COMPATABILITY. It's almost to be considered a completely new program.

P.S.: I probably forgot some changes

### CODE REVIEW

**Comment by PMunch** [comment]
I'll try to make some graphics for the documentation on how the new layout model works as well. Maybe I'll also create a screenshot or two to highlight the new customisability.

**Comment by Tomas-M** [comment]
This is indeed lots of changes.
I will need to test the code in several window managers to see if it behaves correctly in all modes.

**Comment by PMunch** [comment]
Of course, I wasn't expecting this to get merged right away :) I haven't changed the core drawing mechanisms that much so I would be surprised if it wouldn't work across window managers, but testing is always the best approach!

I'm currently working on being able to write to xlunchs stdin while it's running to add and remove entries on the fly. Have it working in my stdinreading branch, but the documentation for it is still a bit incomplete.

Also changed the desktop mode persistance into it's own option --dontquit, -q which allows you to put it in output only mode and read from it's output and update the menu through stdin in an external script.

**Comment by PMunch** [comment]
Sorry for the many commits with all sorts of fixes and features. I think it's now in a state that would be usable by most and modifiable to such a degree it can be used for a lot of various tasks.

Just to show a bit of how it can be customised, [this](http://serv.peterme.net/uploads/xlunch.png) is my current launcher setup. It runs through a [simple script](http://serv.peterme.net/uploads/xlunch-recency) that takes the last entry I chose and puts it at the top of the list, and changes how it is shown based on the orientation of the screen. The transparency of the window is done by compton (I couldn't figure out how to make a transparent background window in X unfortunately), and the window is scaled to just not cover the i3 bar so that it looks like one integrated system. In the i3 config I have used the new WM_CLASS to make all windowed xlunch windows floating and borderless which makes them look like they are fullscreen.

**Comment by PMunch** [comment]
Okay, figured out how to make transparent backgrounds work. So now you can set the background color to transparent and it will be drawn as such (as long as you have a compositor). This also made transparent background images work, so you can create all sorts of effects with that.

**Comment by PMunch** [comment]
So @Tomas-M, had time to test it?

**Comment by Tomas-M** [comment]
gentries script does not work for me. Complains about synax error on line 14, "(" unexpected. I have bash 4.3.30

**Comment by Tomas-M** [comment]
Running with option -d (desktop mode), xlunch should never terminate. But it terminates for me. The point is, in desktop mode, it is running all the time, user clicks icons to run apps as like if he was clicking icons on desktop to run programs, and the desktop itself keeps there. But with your changes, xlunch terminates, which is incorrect behavior.

**Comment by Tomas-M** [comment]
I've merged your changes, please fix the two mentioned problems. Make sure the bash script works on older linuxes, preferably using only old fashioned syntax.

**Comment by PMunch** [comment]
I'll look into the bash problem. I decoupled the desktop mode and the option to never quit (now called --dontquit). This was mostly intended to be able to script since you can now feed it a double newline over stdin to wipe all entries and start over, so you could have a script that listens for input and updates the current running instance of xlunch without having to restart. I could set --dontquit as a default for --desktop but that would mean you can't have a desktop mode that quits on input (should you want that for some reason).

**Comment by PMunch** [comment]
Hmm, it seems to struggle with the array that's created on line 14 which is weird since arrays were introduced in version 2 of bash which was released in 1997.. Maybe you have to add "declare -a formats" before line 14 to explicitly establish formats as an array? This version also uses associative arrays which was introduced in 4.2, released in 2014. But that one is explicitly declared (line 140).

**Comment by Tomas-M** [comment]
Documentation states that in desktop mode, xlunch does not terminate. If there is a --dontquit parameter, it should be at least mentioned in documentation that user should use it with --desktop

**Comment by PMunch** [comment]
It is mentioned in the line "In previous version desktop mode would by default fork of processes instead of terminating. This is now a separate option (--dontquit) so you can keep xlunch running no matter the mode." and shown in the bottom examples with the heading: "To have xlunch running as a desktop with icons in i3wm, add this to ~/.i3/config:". But I guess I should clarify in the --help output and the options overview on the page.

**Comment by PMunch** [comment]
There, my version3 branch now contains updated documentation. Do you want me to open another PR for it? I also noticed that after I changed the links on the documentation page to point to a v3 zip and tar.gz you need to create a release for those in order for the archives to be generated and the links to work.

**Comment by Tomas-M** [comment]
I've added you as collaborant, you should be able to commit to the repo directly.

**Comment by PMunch** [comment]
Hmm, I get permission denied when I try. And even on GitHub when I try to click "New file" it just says I don't have write access.

**Comment by Tomas-M** [comment]
Github shows Awaiting PMunch's response
So maybe you need to firstly somehow accept it. Perhaps click some link in some welcome email? I don't really know. I do not see anywhere to set you different permissions so most likely you should be granted full access by default.

**Comment by PMunch** [comment]
Aha, that was it. I had a pending invitation in my inbox which I just had to accept.

**Pull request merged**
