### PR TITLE
If the user filtered to 1 app, allow him to just press Enter to start it

### PR DESCRIPTION
**Pull request by ghost**
Thanks for your awesome launcher.
I made a little change to allow the user to just press Enter once he filtered to one app.

Before this PR:
Example: you type fi and only have 1 app displaying
image
You have to press Tab once, to select the icon and then you can press Enter to start it.

With this PR:
Once you filtered to only 1 application, you won't have to press Tab to select it anymore, just press Enter.

### CODE REVIEW

**Comment by Tomas-M** [comment]
I'm working on this. You just closed it - is it ready to be merged now?
Thank you

**Comment by Tomas-M** [comment]
Looks like everything works fine so I merged it. Thank you for your patches.

**Comment by lslvr** [comment]
What if on <enter> pressed it executes the first suggestion instead?

**Comment by Tomas-M** [comment]
Not sure what you mean. Please explain in more detail. Thank you.

**Pull request closed without merging**
